# -*- coding: utf-8 -*-
# http://google-styleguide.googlecode.com/svn/trunk/pyguide.html
# {
#    "tasks":[
#       {
#          "vehicleType":{
#             "vehicleTypeID":1,
#             "name":"Car"
#          },
#          "brand":{
#             "brandID":120,
#             "name":"Audi"
#          },
#          "model":{
#             "modelID":1629,
#             "name":"A4"
#          },
#          "engine":{
#             "engineID":7683,
#             "name":"1.9 TDI PD"
#          },
#          "ecu":{
#             "ecuID":19410,
#             "name":"Bosch EDC15P",
#             "secondFile":null
#          },
#          "status":2,
#          "statusName":"Проверено",
#          "task":{
#             "taskID":45416,
#             "createTime":"11/30/2016 07:37:56 PM UTC",
#             "amount":0.0,
#             "paidAmount":0.0,
#             "amountDue":0.0,
#             "allowDownload":false,
#             "currency":null
#          }
#       },
#       {
#          "vehicleType":{
#             "vehicleTypeID":1,
#             "name":"Car"
#          },
#          "brand":{
#             "brandID":128,
#             "name":"Ford"
#          },
#          "model":{
#             "modelID":1762,
#             "name":"Mondeo"
#          },
#          "engine":{
#             "engineID":8260,
#             "name":"2.0 TDCI"
#          },
#          "ecu":{
#             "ecuID":19706,
#             "name":"Siemens/Continental SID202 / SID206",
#             "secondFile":null
#          },
#          "status":2,
#          "statusName":"Проверено",
#          "task":{
#             "taskID":44928,
#             "createTime":"11/27/2016 05:49:57 PM UTC",
#             "amount":0.0,
#             "paidAmount":0.0,
#             "amountDue":0.0,
#             "allowDownload":false,
#             "currency":null
#          }
#       },
#       {
#          "vehicleType":{
#             "vehicleTypeID":1,
#             "name":"Car"
#          },
#          "brand":{
#             "brandID":121,
#             "name":"BMW"
#          },
#          "model":{
#             "modelID":1647,
#             "name":"E46"
#          },
#          "engine":{
#             "engineID":7810,
#             "name":"330i"
#          },
#          "ecu":{
#             "ecuID":19683,
#             "name":"Siemens/Continental MS43",
#             "secondFile":null
#          },
#          "status":5,
#          "statusName":"Обработано",
#          "task":{
#             "taskID":44344,
#             "createTime":"11/22/2016 01:28:32 PM UTC",
#             "amount":0.0,
#             "paidAmount":0.0,
#             "amountDue":0.0,
#             "allowDownload":false,
#             "currency":null
#          }
#       },
#       {
#          "vehicleType":{
#             "vehicleTypeID":1,
#             "name":"Car"
#          },
#          "brand":{
#             "brandID":157,
#             "name":"Volkswagen"
#          },
#          "model":{
#             "modelID":2135,
#             "name":"Golf"
#          },
#          "engine":{
#             "engineID":10046,
#             "name":"2.0 TDI PD"
#          },
#          "ecu":{
#             "ecuID":19436,
#             "name":"Bosch EDC16U34",
#             "secondFile":null
#          },
#          "status":2,
#          "statusName":"Проверено",
#          "task":{
#             "taskID":44250,
#             "createTime":"11/21/2016 07:14:05 PM UTC",
#             "amount":0.0,
#             "paidAmount":0.0,
#             "amountDue":0.0,
#             "allowDownload":false,
#             "currency":null
#          }
#       },
#       {
#          "vehicleType":{
#             "vehicleTypeID":1,
#             "name":"Car"
#          },
#          "brand":{
#             "brandID":157,
#             "name":"Volkswagen"
#          },
#          "model":{
#             "modelID":2141,
#             "name":"Polo"
#          },
#          "engine":{
#             "engineID":10094,
#             "name":"1.6i"
#          },
#          "ecu":{
#             "ecuID":19734,
#             "name":"Siemens/Continental Simos 3",
#             "secondFile":null
#          },
#          "status":5,
#          "statusName":"Обработано",
#          "task":{
#             "taskID":44248,
#             "createTime":"11/21/2016 06:29:58 PM UTC",
#             "amount":0.0,
#             "paidAmount":0.0,
#             "amountDue":0.0,
#             "allowDownload":false,
#             "currency":null
#          }
#       },
#       {
#          "vehicleType":{
#             "vehicleTypeID":1,
#             "name":"Car"
#          },
#          "brand":{
#             "brandID":157,
#             "name":"Volkswagen"
#          },
#          "model":{
#             "modelID":2135,
#             "name":"Golf"
#          },
#          "engine":{
#             "engineID":11053,
#             "name":"2.8i V6"
#          },
#          "ecu":{
#             "ecuID":19512,
#             "name":"Bosch ME7.1",
#             "secondFile":null
#          },
#          "status":3,
#          "statusName":"Недопустимо",
#          "task":{
#             "taskID":44246,
#             "createTime":"11/21/2016 06:25:15 PM UTC",
#             "amount":0.0,
#             "paidAmount":0.0,
#             "amountDue":0.0,
#             "allowDownload":false,
#             "currency":null
#          }
#       },
#       {
#          "vehicleType":{
#             "vehicleTypeID":1,
#             "name":"Car"
#          },
#          "brand":{
#             "brandID":146,
#             "name":"Peugeot"
#          },
#          "model":{
#             "modelID":2014,
#             "name":"407"
#          },
#          "engine":{
#             "engineID":9519,
#             "name":"2.0 HDi"
#          },
#          "ecu":{
#             "ecuID":19712,
#             "name":"Siemens/Continental SID803",
#             "secondFile":null
#          },
#          "status":9,
#          "statusName":"Завершено",
#          "task":{
#             "taskID":43932,
#             "createTime":"11/18/2016 12:13:04 PM UTC",
#             "amount":58.1300,
#             "paidAmount":0.0,
#             "amountDue":58.1300,
#             "allowDownload":false,
#             "currency":null
#          }
#       },
#       {
#          "vehicleType":{
#             "vehicleTypeID":1,
#             "name":"Car"
#          },
#          "brand":{
#             "brandID":157,
#             "name":"Volkswagen"
#          },
#          "model":{
#             "modelID":2138,
#             "name":"Passat"
#          },
#          "engine":{
#             "engineID":10073,
#             "name":"2.0 TDI PD"
#          },
#          "ecu":{
#             "ecuID":19699,
#             "name":"Siemens/Continental PPD1.5",
#             "secondFile":null
#          },
#          "status":5,
#          "statusName":"Обработано",
#          "task":{
#             "taskID":40489,
#             "createTime":"10/19/2016 01:07:10 PM UTC",
#             "amount":0.0,
#             "paidAmount":0.0,
#             "amountDue":0.0,
#             "allowDownload":false,
#             "currency":null
#          }
#       }
#    ],
#    "totalCount":8
# }